plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
    id "org.jetbrains.kotlin.plugin.compose"
}

android {
    namespace "com.autonavi.minimap"
    compileSdkVersion "android-37.0"

    defaultConfig {
        applicationId "com.autonavi.minimap"
        minSdk 27
        targetSdk 36
        versionCode 135
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    compileOnly project(":xposed-api-stub")
    implementation "androidx.activity:activity-compose:1.12.4"
    implementation "androidx.core:core-ktx:1.17.0"
    implementation "top.yukonga.miuix.kmp:miuix-ui-android:0.9.2"
    implementation "androidx.compose.material:material-icons-extended:1.7.8"
    implementation "androidx.compose.material3:material3:1.4.0"
    implementation "androidx.compose.ui:ui-tooling-preview:1.10.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0"
    implementation "androidx.lifecycle:lifecycle-runtime-compose:2.10.0"
    implementation "androidx.media:media:1.8.0"
    debugImplementation "androidx.compose.ui:ui-tooling:1.10.1"
}
